arr = []
arr2 = []
arr.append(1)
arr.append(2)
arr.append(3)
arr.append(4)
arr2.append(arr.pop())
arr2.append(arr.pop())
arr.append(5)
arr.append(6)
arr2.append(arr.pop())
arr.append(7)
arr.append(8)
arr2.append(arr.pop())
arr2.append(arr.pop())
arr2.append(arr.pop())
arr2.append(arr.pop())
arr2.append(arr.pop())
print(arr , arr2)